version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

    # If needed, mount volumes (optional for dev)
    # volumes:
    #   - ./backend:/app

    # Optional restart policy
    restart: unless-stopped
